//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwshKeePass.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PwshKeePass.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution failed because a background thread could not prompt the user..
        /// </summary>
        public static string BaseShouldMethodFailureReason {
            get {
                return ResourceManager.GetString("BaseShouldMethodFailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate was found in the certificate store with thumbprint {0}.
        /// </summary>
        public static string CertificateNotFoundInStore {
            get {
                return ResourceManager.GetString("CertificateNotFoundInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal characters in path..
        /// </summary>
        public static string IllegalPath {
            get {
                return ResourceManager.GetString("IllegalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate format. Publish settings may be corrupted. Use Get-AzurePublishSettingsFile to download updated settings.
        /// </summary>
        public static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate format..
        /// </summary>
        public static string InvalidCertificateSingle {
            get {
                return ResourceManager.GetString("InvalidCertificateSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is an invalid DNS name for {1}.
        /// </summary>
        public static string InvalidDnsName {
            get {
                return ResourceManager.GetString("InvalidDnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided file in {0} must be have {1} extension.
        /// </summary>
        public static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has invalid characters.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} provided is not a valid GUID. Please provide a valid GUID..
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified hostname does not exist. Please specify a valid hostname for the site..
        /// </summary>
        public static string InvalidHostnameValidation {
            get {
                return ResourceManager.GetString("InvalidHostnameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} instances must be greater than or equal 0 and less than or equal 20.
        /// </summary>
        public static string InvalidInstancesCount {
            get {
                return ResourceManager.GetString("InvalidInstancesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating your webjob. Please make sure that the script is in the root folder of the zip file..
        /// </summary>
        public static string InvalidJobFile {
            get {
                return ResourceManager.GetString("InvalidJobFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download a valid runtime manifest, Please check your internet connection and try again..
        /// </summary>
        public static string InvalidManifestError {
            get {
                return ResourceManager.GetString("InvalidManifestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name &quot;{0}&quot; does not match the service bus namespace naming rules..
        /// </summary>
        public static string InvalidNamespaceName {
            get {
                return ResourceManager.GetString("InvalidNamespaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null. Parameter name: &apos;{0}&apos;.
        /// </summary>
        public static string InvalidNullArgument {
            get {
                return ResourceManager.GetString("InvalidNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid or empty.
        /// </summary>
        public static string InvalidOrEmptyArgumentMessage {
            get {
                return ResourceManager.GetString("InvalidOrEmptyArgumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided package path is invalid or doesn&apos;t exist.
        /// </summary>
        public static string InvalidPackagePath {
            get {
                return ResourceManager.GetString("InvalidPackagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid parameter set name..
        /// </summary>
        public static string InvalidParameterSetName {
            get {
                return ResourceManager.GetString("InvalidParameterSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist in {1} or you&apos;ve not passed valid value for it.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} has invalid characters.
        /// </summary>
        public static string InvalidPathName {
            get {
                return ResourceManager.GetString("InvalidPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided role name &quot;{0}&quot; has invalid characters.
        /// </summary>
        public static string InvalidRoleNameMessage {
            get {
                return ResourceManager.GetString("InvalidRoleNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid name for the service root folder is required.
        /// </summary>
        public static string InvalidRootNameMessage {
            get {
                return ResourceManager.GetString("InvalidRootNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a recognized runtime type.
        /// </summary>
        public static string InvalidRuntimeError {
            get {
                return ResourceManager.GetString("InvalidRuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PwshKeePass Long-Running Job.
        /// </summary>
        public static string LROJobName {
            get {
                return ResourceManager.GetString("LROJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlet failed in background execution.  The returned error was &apos;{0}&apos;.  Please execute the cmdlet again.  You may need to execute this cmdlet synchronously, by omitting the &apos;-AsJob&apos; parameter..
        /// </summary>
        public static string LROTaskExceptionMessage {
            get {
                return ResourceManager.GetString("LROTaskExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to internet before executing this cmdlet.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NONE&gt;.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} doesn&apos;t exist..
        /// </summary>
        public static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path for {0} doesn&apos;t exist in {1}..
        /// </summary>
        public static string PathDoesNotExistForElement {
            get {
                return ResourceManager.GetString("PathDoesNotExistForElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided service name {0} already exists, please pick another name.
        /// </summary>
        public static string ServiceNameExists {
            get {
                return ResourceManager.GetString("ServiceNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please execute the cmdlet again and include the &apos;Force&apos; parameter, if available, to avoid unnecessary prompts..
        /// </summary>
        public static string ShouldContinueFail {
            get {
                return ResourceManager.GetString("ShouldContinueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ShouldProcessCaption {
            get {
                return ResourceManager.GetString("ShouldProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please execute the cmdlet again and omit the &apos;Confirm&apos; parameter when using the &apos;AsJob&apos; parameter..
        /// </summary>
        public static string ShouldProcessFailConfirm {
            get {
                return ResourceManager.GetString("ShouldProcessFailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please increase the user $ConfirmPreference setting, or include turn off confirmation using &apos;-Confirm:$false&apos; when using the &apos;AsJob&apos; parameter and execute the cmdet again..
        /// </summary>
        public static string ShouldProcessFailImpact {
            get {
                return ResourceManager.GetString("ShouldProcessFailImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please execute the cmdlet again and omit the &apos;WhatIf&apos; parameter when using the &apos;AsJob&apos; parameter..
        /// </summary>
        public static string ShouldProcessFailWhatIf {
            get {
                return ResourceManager.GetString("ShouldProcessFailWhatIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Starting cmdlet execution, setting for cmdlet confirmation required: &apos;{0}&apos;.
        /// </summary>
        public static string TraceBeginLROJob {
            get {
                return ResourceManager.GetString("TraceBeginLROJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Blocking job for ShouldMethod &apos;{0}&apos;.
        /// </summary>
        public static string TraceBlockLROThread {
            get {
                return ResourceManager.GetString("TraceBlockLROThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Completing cmdlet execution in RunJob.
        /// </summary>
        public static string TraceEndLROJob {
            get {
                return ResourceManager.GetString("TraceEndLROJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: State change from &apos;{0}&apos; to &apos;{1}&apos; because &apos;{2}&apos;.
        /// </summary>
        public static string TraceHandleLROStateChange {
            get {
                return ResourceManager.GetString("TraceHandleLROStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Unblocking job due to stoppage or failure.
        /// </summary>
        public static string TraceHandlerCancelJob {
            get {
                return ResourceManager.GetString("TraceHandlerCancelJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Unblocking job that was previously blocked..
        /// </summary>
        public static string TraceHandlerUnblockJob {
            get {
                return ResourceManager.GetString("TraceHandlerUnblockJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Error in cmdlet execution.
        /// </summary>
        public static string TraceLROJobException {
            get {
                return ResourceManager.GetString("TraceLROJobException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: Removing state changed event handler, exception &apos;{0}&apos;.
        /// </summary>
        public static string TraceRemoveLROEventHandler {
            get {
                return ResourceManager.GetString("TraceRemoveLROEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KeePassLongRunningJob]: ShouldMethod &apos;{0}&apos; unblocked..
        /// </summary>
        public static string TraceUnblockLROThread {
            get {
                return ResourceManager.GetString("TraceUnblockLROThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update mismatching Json structured: {0} {1}..
        /// </summary>
        public static string UnableToPatchJson {
            get {
                return ResourceManager.GetString("UnableToPatchJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (x86).
        /// </summary>
        public static string x86InProgramFiles {
            get {
                return ResourceManager.GetString("x86InProgramFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I agree.
        /// </summary>
        public static string YesHint {
            get {
                return ResourceManager.GetString("YesHint", resourceCulture);
            }
        }
    }
}
